### ISSUE TITLE
list of figures and list of tables not in rendered PDF

### ISSUE THREAD

**Issue by ricardd** [pbs-assess/csasdowntex#38] opened 2019-03-26 16:48 UTC
In index.Rmd, there are two lines:

```
lot: true
lof: true
```

but the list of figures and list of tables do not appear in the rendered PDF. 

Is there something special to do in order for the LOF and LOT to appear?

**Comment by seananderson** [comment] 2019-03-26 16:50
Yes, you would need to integrate it into the .tex or .sty files using whatever the TeX code would be. We haven't been including those because apparently CSAS doesn't require it.

**Comment by seananderson** [comment] 2019-03-29 16:20
I confirmed a couple days ago that this is not required by CSAS. I don't plan to implement this but if somebody else wants to they are welcome. I'll leave this open for a while and close it eventually.

**Comment by cgrandin** [comment] 2019-03-29 18:38
They actually told me at some point that we CANNOT include them so I stopped doing it. Since then I have seen them included in other documents. I prefer not to bother since we have live links for everything in the docs now.

**Comment by ricardd** [comment] 2019-03-30 01:10
we should check with Ottawa on whether we should or should not do this, because a ResDoc with LoT and LoF was recently published with their consent:

http://www.dfo-mpo.gc.ca/csas-sccs/Publications/ResDocs-DocRech/2019/2019_002-eng.html

**Comment by seananderson** [comment] 2019-03-30 02:34
Latest word I’ve heard is that it’s optional. There are recent published examples with and without.

**Comment by ricardd** [comment] 2021-05-04 12:45
Could we use the same argument `lot_lof` that is used for ResDocs in TechReports as well?

**Comment by seananderson** [comment] 2021-05-04 18:46
Yes, it would be good to match. Just a matter of implementing this.

**Closed as completed** 2021-05-05 13:07 UTC
Labels: enhancement
